{{- if and .Values.persistence.data.enabled (not .Values.persistence.data.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "hemmelig.fullname" . }}-data
  labels:
    {{- include "hemmelig.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.data.accessMode }}
  {{- if .Values.persistence.data.storageClass }}
  storageClassName: {{ .Values.persistence.data.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size }}
{{- end }}
{{- if and .Values.persistence.uploads.enabled (not .Values.persistence.uploads.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "hemmelig.fullname" . }}-uploads
  labels:
    {{- include "hemmelig.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.uploads.accessMode }}
  {{- if .Values.persistence.uploads.storageClass }}
  storageClassName: {{ .Values.persistence.uploads.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.uploads.size }}
{{- end }}
