{{- if and (or .Values.config.betterAuthSecret (or .Values.oauth.github.enabled (or .Values.oauth.google.enabled (or .Values.oauth.microsoft.enabled (or .Values.oauth.discord.enabled (or .Values.oauth.gitlab.enabled (or .Values.oauth.apple.enabled (or .Values.oauth.twitter.enabled .Values.oauth.generic)))))))) (not .Values.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hemmelig.fullname" . }}
  labels:
    {{- include "hemmelig.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.config.betterAuthSecret }}
  BETTER_AUTH_SECRET: {{ .Values.config.betterAuthSecret | b64enc | quote }}
  {{- end }}
  {{- if .Values.oauth.github.enabled }}
  {{- if .Values.oauth.github.clientId }}
  HEMMELIG_AUTH_GITHUB_ID: {{ .Values.oauth.github.clientId | b64enc | quote }}
  {{- end }}
  {{- if .Values.oauth.github.clientSecret }}
  HEMMELIG_AUTH_GITHUB_SECRET: {{ .Values.oauth.github.clientSecret | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- if .Values.oauth.google.enabled }}
  {{- if .Values.oauth.google.clientId }}
  HEMMELIG_AUTH_GOOGLE_ID: {{ .Values.oauth.google.clientId | b64enc | quote }}
  {{- end }}
  {{- if .Values.oauth.google.clientSecret }}
  HEMMELIG_AUTH_GOOGLE_SECRET: {{ .Values.oauth.google.clientSecret | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- if .Values.oauth.microsoft.enabled }}
  {{- if .Values.oauth.microsoft.clientId }}
  HEMMELIG_AUTH_MICROSOFT_ID: {{ .Values.oauth.microsoft.clientId | b64enc | quote }}
  {{- end }}
  {{- if .Values.oauth.microsoft.clientSecret }}
  HEMMELIG_AUTH_MICROSOFT_SECRET: {{ .Values.oauth.microsoft.clientSecret | b64enc | quote }}
  {{- end }}
  {{- if .Values.oauth.microsoft.tenantId }}
  HEMMELIG_AUTH_MICROSOFT_TENANT_ID: {{ .Values.oauth.microsoft.tenantId | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- if .Values.oauth.discord.enabled }}
  {{- if .Values.oauth.discord.clientId }}
  HEMMELIG_AUTH_DISCORD_ID: {{ .Values.oauth.discord.clientId | b64enc | quote }}
  {{- end }}
  {{- if .Values.oauth.discord.clientSecret }}
  HEMMELIG_AUTH_DISCORD_SECRET: {{ .Values.oauth.discord.clientSecret | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- if .Values.oauth.gitlab.enabled }}
  {{- if .Values.oauth.gitlab.clientId }}
  HEMMELIG_AUTH_GITLAB_ID: {{ .Values.oauth.gitlab.clientId | b64enc | quote }}
  {{- end }}
  {{- if .Values.oauth.gitlab.clientSecret }}
  HEMMELIG_AUTH_GITLAB_SECRET: {{ .Values.oauth.gitlab.clientSecret | b64enc | quote }}
  {{- end }}
  {{- if .Values.oauth.gitlab.issuer }}
  HEMMELIG_AUTH_GITLAB_ISSUER: {{ .Values.oauth.gitlab.issuer | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- if .Values.oauth.apple.enabled }}
  {{- if .Values.oauth.apple.clientId }}
  HEMMELIG_AUTH_APPLE_ID: {{ .Values.oauth.apple.clientId | b64enc | quote }}
  {{- end }}
  {{- if .Values.oauth.apple.clientSecret }}
  HEMMELIG_AUTH_APPLE_SECRET: {{ .Values.oauth.apple.clientSecret | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- if .Values.oauth.twitter.enabled }}
  {{- if .Values.oauth.twitter.clientId }}
  HEMMELIG_AUTH_TWITTER_ID: {{ .Values.oauth.twitter.clientId | b64enc | quote }}
  {{- end }}
  {{- if .Values.oauth.twitter.clientSecret }}
  HEMMELIG_AUTH_TWITTER_SECRET: {{ .Values.oauth.twitter.clientSecret | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- if .Values.oauth.generic }}
  HEMMELIG_AUTH_GENERIC_OAUTH: {{ .Values.oauth.generic | b64enc | quote }}
  {{- end }}
{{- end }}
