{{- if and .Values.config.betterAuthSecret (not .Values.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hemmelig.fullname" . }}
  labels:
    {{- include "hemmelig.labels" . | nindent 4 }}
type: Opaque
data:
  BETTER_AUTH_SECRET: {{ .Values.config.betterAuthSecret | b64enc | quote }}
{{- end }}
