name: Publish Docker image
on:
    release:
        types: [published]
jobs:
    push_to_registry:
        name: Push Docker image to Docker Hub
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v3
            # Workaround: https://github.com/docker/build-push-action/issues/461
            - name: Setup Docker buildx
              uses: docker/setup-buildx-action@v2.4.1
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2.1.0

            - name: Log in to Docker Hub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
            - name: Get latest git tag
              id: latest_tag
              uses: 'WyriHaximus/github-action-get-previous-tag@v1'
              with:
                  fallback: no-tag

            - name: Get short SHA
              id: short_sha
              run: echo "sha=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT

            - name: Get major version
              id: major_version
              run: |
                  echo "version=$(echo ${{ steps.latest_tag.outputs.tag }} | cut -d'.' -f1)" >> $GITHUB_OUTPUT

            - name: Get minor version
              id: minor_version
              run: |
                  echo "version=$(echo ${{ steps.latest_tag.outputs.tag }} | cut -d'.' -f1,2)" >> $GITHUB_OUTPUT

            - name: Push to Docker Hub (latest)
              uses: docker/build-push-action@v4
              with:
                  platforms: linux/amd64, linux/arm64
                  push: true
                  tags: hemmeligapp/hemmelig:latest
                  build-args: |
                      GIT_SHA=${{ steps.short_sha.outputs.sha }}
                      GIT_TAG=${{ steps.latest_tag.outputs.tag }}

            - name: Push to Docker Hub (full version)
              uses: docker/build-push-action@v4
              with:
                  platforms: linux/amd64, linux/arm64
                  push: true
                  tags: hemmeligapp/hemmelig:${{ steps.latest_tag.outputs.tag }}
                  build-args: |
                      GIT_SHA=${{ steps.short_sha.outputs.sha }}
                      GIT_TAG=${{ steps.latest_tag.outputs.tag }}

            - name: Push to Docker Hub (minor version)
              uses: docker/build-push-action@v4
              with:
                  platforms: linux/amd64, linux/arm64
                  push: true
                  tags: hemmeligapp/hemmelig:${{ steps.minor_version.outputs.version }}
                  build-args: |
                      GIT_SHA=${{ steps.short_sha.outputs.sha }}
                      GIT_TAG=${{ steps.latest_tag.outputs.tag }}

            - name: Push to Docker Hub (major version)
              uses: docker/build-push-action@v4
              with:
                  platforms: linux/amd64, linux/arm64
                  push: true
                  tags: hemmeligapp/hemmelig:${{ steps.major_version.outputs.version }}
                  build-args: |
                      GIT_SHA=${{ steps.short_sha.outputs.sha }}
                      GIT_TAG=${{ steps.latest_tag.outputs.tag }}
